output_dir: dvclive/artifacts
overwrite_output_dir: false
do_train: false
do_eval: true
do_predict: false
evaluation_strategy: steps
prediction_loss_only: false
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
per_gpu_train_batch_size:
per_gpu_eval_batch_size:
gradient_accumulation_steps: 1
eval_accumulation_steps:
eval_delay: 0
learning_rate: 0.0002
weight_decay: 0.001
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-08
max_grad_norm: 1.0
num_train_epochs: 1
max_steps: -1
lr_scheduler_type: constant
warmup_ratio: 0.03
warmup_steps: 0
log_level: passive
log_level_replica: warning
log_on_each_node: true
logging_dir: dvclive/artifacts/runs/Sep01_15-57-40_ip-172-31-39-255
logging_strategy: steps
logging_first_step: false
logging_steps: 10
logging_nan_inf_filter: true
save_strategy: steps
save_steps: 20
save_total_limit: 1
save_safetensors: false
save_on_each_node: false
no_cuda: false
use_cpu: false
use_mps_device: false
seed: 42
data_seed:
jit_mode_eval: false
use_ipex: false
bf16: true
fp16: false
fp16_opt_level: O1
half_precision_backend: auto
bf16_full_eval: false
fp16_full_eval: false
tf32:
local_rank: 0
ddp_backend:
tpu_num_cores:
tpu_metrics_debug: false
debug: []
dataloader_drop_last: false
eval_steps: 10
dataloader_num_workers: 0
past_index: -1
run_name: dvclive/artifacts
disable_tqdm: false
remove_unused_columns: true
label_names:
load_best_model_at_end: true
metric_for_best_model: loss
greater_is_better: false
ignore_data_skip: false
sharded_ddp: []
fsdp: []
fsdp_min_num_params: 0
fsdp_config:
  min_num_params: 0
  xla: false
  xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
deepspeed:
label_smoothing_factor: 0.0
optim: paged_adamw_32bit
optim_args:
adafactor: false
group_by_length: true
length_column_name: length
report_to:
- wandb
ddp_find_unused_parameters:
ddp_bucket_cap_mb:
ddp_broadcast_buffers:
dataloader_pin_memory: true
skip_memory_metrics: true
use_legacy_prediction_loop: false
push_to_hub: false
resume_from_checkpoint:
hub_model_id:
hub_strategy: every_save
hub_token: <HUB_TOKEN>
hub_private_repo: false
hub_always_push: false
gradient_checkpointing: false
include_inputs_for_metrics: false
fp16_backend: auto
push_to_hub_model_id:
push_to_hub_organization:
push_to_hub_token: <PUSH_TO_HUB_TOKEN>
mp_parameters: ''
auto_find_batch_size: false
full_determinism: false
torchdynamo:
ray_scope: last
ddp_timeout: 1800
torch_compile: false
torch_compile_backend:
torch_compile_mode:
dispatch_batches:
